version: '3.8'
services:
  controller:
    image: ngrinder/controller
    container_name: ngrinder-controller
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8888:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent
    container_name: ngrinder-agent
    platform: linux/amd64
    restart: unless-stopped
    links:
      - controller