# h2 db 자료 : https://www.h2database.com/html/cheatSheet.html

server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:test  # 인메모리 테스트용 - db 확인 안됨
    #    url: jdbc:h2:~/notice
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: error-messages